// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.karoid.preview-table",
    "name": "Preview Table",
    "description": "This plugin adds functionality for table preview.",
    "homepage_url": "https://github.com/Karoid/mattermost-plugin-preview-table",
    "support_url": "https://github.com/Karoid/mattermost-plugin-preview-table/issues",
    "icon_path": "assets/preview-table.svg",
    "version": "0.1.0",
    "min_server_version": "6.2.1",
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": []
    }
}
`);

export default manifest;
